[package]
name = "code-brute"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1"
regex = "1.5.4"
num_cpus = "1.13.0"
itertools = "0.10.1"
quick-js= "0.4.1"
rand = "0.8.4"
rpn= "0.1.0"